// Frozen design system injected verbatim into every generated build prompt.
// Deliberately NOT generated by an LLM — earlier iterations asked a free-tier
// model to "write a detailed prompt" from scratch each time, and techniques
// described only in prose got diluted or dropped in paraphrase. Freezing the
// chassis as code guarantees every build gets the full, exact technique set.
export const CORE_CHASSIS = `## CORE DESIGN SYSTEM — apply on every build, exactly as follows.

Build the site using a single continuous design system — no section should
read as a separate flat block. Follow these structural rules throughout:

BACKGROUND CONTINUITY:
- Use ONE continuous background treatment (gradient mesh, subtle noise/glow,
  or gradient wash) that runs behind the entire page length.
- Do NOT give each section its own flat solid background color. Sections are
  content placed on top of the continuous background, not separate colored
  boxes stacked vertically.
- Where a section does need visual separation, use a soft gradient blend
  transition (fade), never a hard color-to-color cut.

SECTION BLEED:
- At least one element per section (an image, card, or shape) should overlap
  or bleed across the boundary into the next section, so no section starts
  with a clean flat edge.
- Avoid uniform padding boxes around every section — let content breathe
  asymmetrically instead of centering everything in identical containers.

SPATIAL 3D DEPTH (this site's signature futuristic quality):
- Use real CSS 3D transforms, not just shadows: apply \`perspective\` on
  section containers and \`transform-style: preserve-3d\` with
  \`rotateX\`/\`rotateY\`/\`translateZ\` on cards, panels, and floating UI
  snippets so they occupy genuine layered depth, not flat 2D layering.
- Implement cursor-driven tilt: on desktop, panels/cards subtly rotate toward
  the cursor position via a vanilla-JS mousemove listener (small range, e.g.
  -6deg to 6deg, eased/damped — never a jarring or full 3D spin).
- Implement scroll-driven depth parallax: distinct layers (background,
  midground panels, foreground UI elements) translate/scale at different
  rates as the user scrolls, so the page feels like it has physical z-depth,
  not just a list of sections.
- Floating elements should look like they hover above the background plane —
  combine translateZ with a soft diffused shadow (see SURFACES below) and a
  very subtle idle float animation (a few px of vertical drift on a slow
  loop) so panels feel alive even without cursor/scroll interaction.
- All of this is plain CSS + vanilla JS only — no WebGL, no three.js, no
  canvas libraries, no build step.
- Respect \`prefers-reduced-motion\`: when set, disable all tilt/parallax
  motion entirely (elements render in their resting position, no listeners
  attached). On touch devices, disable cursor-tilt outright (no cursor
  exists) and keep scroll-parallax simplified — fewer simultaneously
  animated layers — to protect performance on lower-end phones.

DEPTH & DIMENSIONALITY:
- Layer elements (cards, images, UI snippets) at slightly different apparent
  depths using size, blur, and shadow, in addition to the literal 3D
  transforms above — not instead of them.
- All shadows and glows must share ONE consistent light direction/intensity
  across the entire page (e.g., soft shadow bottom-right on every card).
  This consistency is what sells "dimensional" over "flat."
- Depth cues: subtle box-shadow (soft, diffused, low opacity), backdrop-blur
  on any translucent/glass panels, slight scale or rotation offsets on
  floating elements (1-3 degrees max, not garish).

SURFACES & EDGES:
- Every card, button, image, and container uses generous consistent
  border-radius (no sharp 90° corners anywhere on the site).
- Borders, if used at all, are low-opacity (5-15%) hairlines — never a hard
  solid-color border.
- Glass/translucent panels: semi-transparent dark or light fill +
  backdrop-filter blur + soft border-glow, used for any floating UI card,
  stat callout, or overlay element.

MOTION:
- Elements should feel like they drift/float at slightly different speeds on
  scroll (parallax) rather than moving in lockstep.
- Transitions between states/sections use smooth easing curves, never
  abrupt cuts.
- Avoid motion that resets or "restarts" the page feel at each section —
  motion should feel like one continuous scroll experience.

TYPOGRAPHY RHYTHM:
- Establish one clear type-scale hierarchy and use it identically across all
  sections (same kicker style, same headline style, same body style
  everywhere) — this repetition is part of what makes it feel cohesive
  rather than assembled from different templates.
- Optional signature move: pair one bold/heavy weight with one lighter or
  italic/serif weight in headlines for a tension point — but keep this
  pairing IDENTICAL across every section that uses it.

WHAT TO AVOID:
- Flat white/gray "template" section backgrounds with hard-edged containers
- Uniform grid-locked card layouts with identical spacing (reads as generic
  builder output)
- Hard drop-shadows with visible edges (looks like Word Art, not depth)
- Mixed border-radius values across the same page
- Section dividers as literal horizontal lines
- Flat, non-dimensional cards/panels that ignore the SPATIAL 3D DEPTH rules
  above`;

export const NON_NEGOTIABLE_CONSTRAINTS = `## NON-NEGOTIABLE CONSTRAINTS

(1) Any decorative or overlapping visual element (tags, rotated blocks,
oversized numerals, pull-quotes, etc.) is positioned only over genuinely
empty space and must never overlap or obscure body copy or headline text at
any breakpoint (desktop, tablet, mobile) — check every section at 1440px,
768px, and 375px before considering the build done; relocate or remove on
collision.

(2) At least one element per major section visually breaks out of the
centered content container (e.g. a full-bleed image or color block using a
100vw/negative-margin breakout technique), and feature/offering sections use
irregular, unequal column spans rather than a symmetric row of equal-width
cards — a generic evenly-spaced three- or four-card grid is explicitly not
acceptable.

(3) Every major section (hero, philosophy/manifesto, each feature/offering
block or between offering pairs, process, footer) includes at least one
distinct image or illustrative visual of its own — a page carrying most of
its content as pure typography/color blocks with only one or two images
total for the whole site is not acceptable. Vary the imagery treatment
across sections (some full-bleed photographic, some smaller inline
illustrative accents, different AI-image prompts per section) rather than
reusing the same one or two visuals throughout.`;
